<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySqlConnector" Version="2.6.2" />
    <EmbeddedResource Include="Database\001_usuarios.sql" />
    <Compile Remove="tests\**\*.cs" />
    <Content Remove="tests\**" />
    <None Remove="tests\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
  </ItemGroup>

</Project>
